import React, { useState } from 'react';
import type { WebsitePage } from '../../../types';
import { AccordionGroup, TextInput } from '../inputs';
// useState + TextInput are still used inside PageRow's inline rename form
// below — keep the imports.

// Pages in this builder are auto-generated by the backend (homepage,
// services, area pages, etc.) — the user shouldn't be creating them by hand.
// We keep onAddPage in the prop interface as optional so the wiring chain
// in App.tsx / GlobalThemePanel doesn't need to change, and re-enabling
// manual creation later is a one-line UI revert.
interface PagesPanelProps {
  pages: WebsitePage[];
  currentPageId: string | undefined;
  onSelectPage: (pageId: string) => void;
  onAddPage?: (name: string, slug: string) => void;
  onRenamePage: (pageId: string, name: string, slug: string) => void;
  onDeletePage: (pageId: string) => void;
  onReorderPage: (pageId: string, direction: 'up' | 'down') => void;
}

/** A single page row in the list — inline editable. */
const PageRow: React.FC<{
  page: WebsitePage;
  isActive: boolean;
  canMoveUp: boolean;
  canMoveDown: boolean;
  canDelete: boolean;
  onSelect: () => void;
  onRename: (name: string, slug: string) => void;
  onDelete: () => void;
  onMoveUp: () => void;
  onMoveDown: () => void;
}> = ({ page, isActive, canMoveUp, canMoveDown, canDelete, onSelect, onRename, onDelete, onMoveUp, onMoveDown }) => {
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(page.name);
  const [slug, setSlug] = useState(page.slug);

  const save = () => {
    if (!name.trim()) return;
    onRename(name.trim(), slug.trim() || '/');
    setEditing(false);
  };

  if (editing) {
    return (
      <div className="p-2 bg-[#151515] border border-blue-500/50 rounded space-y-2">
        <TextInput label="Name" value={name} onChange={setName} placeholder="About" />
        <TextInput label="URL Slug" value={slug} onChange={setSlug} placeholder="/about" />
        <div className="flex gap-2">
          <button
            type="button"
            onClick={save}
            className="flex-1 px-2 py-1 bg-blue-600/20 hover:bg-blue-600/30 text-blue-400 rounded border border-blue-600/30 text-[10px] focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"
          >Save</button>
          <button
            type="button"
            onClick={() => { setEditing(false); setName(page.name); setSlug(page.slug); }}
            className="flex-1 px-2 py-1 bg-white/5 hover:bg-white/10 text-white/60 rounded border border-white/10 text-[10px] focus:outline-none focus-visible:ring-2 focus-visible:ring-white/30"
          >Cancel</button>
        </div>
      </div>
    );
  }

  return (
    <div
      className={`group flex items-center gap-1 p-2 rounded border text-[11px] transition-all ${
        isActive
          ? 'bg-blue-500/10 border-blue-500/50'
          : 'bg-[#151515] border-[#2a2a2a] hover:border-[#444]'
      }`}
    >
      <button
        type="button"
        onClick={onSelect}
        className="flex-1 flex items-center gap-2 text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 rounded"
        aria-label={`Switch to page ${page.name}`}
      >
        <i className={`fa-solid fa-file text-[10px] ${isActive ? 'text-blue-400' : 'text-white/40'}`} aria-hidden="true"></i>
        <div className="min-w-0 flex-1">
          <div className={`truncate font-medium ${isActive ? 'text-white' : 'text-white/80'}`}>{page.name}</div>
          <div className="text-[9px] text-white/40 truncate font-mono">{page.slug}</div>
        </div>
      </button>
      <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 focus-within:opacity-100 transition-opacity">
        <button
          type="button"
          onClick={onMoveUp}
          disabled={!canMoveUp}
          title="Move up"
          aria-label={`Move ${page.name} up`}
          className="w-5 h-5 flex items-center justify-center rounded hover:bg-white/10 text-white/40 disabled:opacity-30 focus:outline-none focus-visible:ring-1 focus-visible:ring-blue-500"
        >
          <i className="fa-solid fa-chevron-up text-[8px]" aria-hidden="true"></i>
        </button>
        <button
          type="button"
          onClick={onMoveDown}
          disabled={!canMoveDown}
          title="Move down"
          aria-label={`Move ${page.name} down`}
          className="w-5 h-5 flex items-center justify-center rounded hover:bg-white/10 text-white/40 disabled:opacity-30 focus:outline-none focus-visible:ring-1 focus-visible:ring-blue-500"
        >
          <i className="fa-solid fa-chevron-down text-[8px]" aria-hidden="true"></i>
        </button>
        <button
          type="button"
          onClick={() => setEditing(true)}
          title="Rename"
          aria-label={`Rename ${page.name}`}
          className="w-5 h-5 flex items-center justify-center rounded hover:bg-white/10 text-white/40 focus:outline-none focus-visible:ring-1 focus-visible:ring-blue-500"
        >
          <i className="fa-solid fa-pencil text-[8px]" aria-hidden="true"></i>
        </button>
        {canDelete && (
          <button
            type="button"
            onClick={() => {
              if (window.confirm(`Delete page "${page.name}"? This cannot be undone.`)) {
                onDelete();
              }
            }}
            title="Delete page"
            aria-label={`Delete page ${page.name}`}
            className="w-5 h-5 flex items-center justify-center rounded bg-red-500/10 hover:bg-red-500/20 text-red-400 focus:outline-none focus-visible:ring-1 focus-visible:ring-red-500"
          >
            <i className="fa-solid fa-xmark text-[8px]" aria-hidden="true"></i>
          </button>
        )}
      </div>
    </div>
  );
};

/** Pages list panel — switch / rename / reorder / delete. Manual page
 *  creation is intentionally not exposed: pages are produced by the backend
 *  generation pipeline (homepage, services, locations, etc.). */
export const PagesPanel: React.FC<PagesPanelProps> = ({
  pages,
  currentPageId,
  onSelectPage,
  onRenamePage,
  onDeletePage,
  onReorderPage,
}) => {
  return (
    <AccordionGroup title={`Pages (${pages.length})`} defaultOpen={true}>
      <div className="space-y-2">
        {pages.map((page, idx) => (
          <PageRow
            key={page.id}
            page={page}
            isActive={page.id === currentPageId}
            canMoveUp={idx > 0}
            canMoveDown={idx < pages.length - 1}
            canDelete={pages.length > 1}
            onSelect={() => onSelectPage(page.id)}
            onRename={(name, slug) => onRenamePage(page.id, name, slug)}
            onDelete={() => onDeletePage(page.id)}
            onMoveUp={() => onReorderPage(page.id, 'up')}
            onMoveDown={() => onReorderPage(page.id, 'down')}
          />
        ))}
      </div>
    </AccordionGroup>
  );
};
