import { ElementPropertyGroup } from './index';
import { getPropertyDefaultValue } from './defaults';

// Get all defaults from unified defaults (single source of truth)
const getDefault = (key: string) => getPropertyDefaultValue('textarea', key);

export const textareaProperties: ElementPropertyGroup = {
  elementId: 'textarea',
  displayName: 'Textarea',
  properties: {
    content: [
      {
        key: 'placeholder',
        label: 'Placeholder',
        type: 'text',
        defaultValue: getDefault('placeholder'),
        placeholder: 'Placeholder text',
        category: 'content',
      },
      {
        key: 'value',
        label: 'Default Value',
        type: 'textarea',
        defaultValue: getDefault('value'),
        placeholder: 'Default textarea value',
        category: 'content',
      },
      {
        key: 'name',
        label: 'Field Name',
        type: 'text',
        defaultValue: getDefault('name'),
        placeholder: 'Field name for form submission',
        category: 'content',
      },
      {
        key: 'rows',
        label: 'Rows',
        type: 'number',
        defaultValue: getDefault('rows'),
        min: 1,
        max: 20,
        category: 'content',
      },
    ],
    style: [
      {
        key: 'borderRadius',
        label: 'Border Radius',
        type: 'text',
        defaultValue: getDefault('borderRadius'),
        placeholder: 'e.g., 6px, 50%',
        category: 'style',
      },
      {
        key: 'border',
        label: 'Border',
        type: 'text',
        defaultValue: getDefault('border'),
        placeholder: 'e.g., 1px solid #ccc',
        category: 'style',
      },
      {
        key: 'fontSize',
        label: 'Font Size',
        type: 'text',
        defaultValue: getDefault('fontSize'),
        placeholder: 'e.g., 1rem, 16px',
        category: 'style',
      },
      {
        key: 'width',
        label: 'Width',
        type: 'text',
        defaultValue: getDefault('width'),
        placeholder: 'e.g., 100%, 300px',
        category: 'style',
      },
      {
        key: 'minHeight',
        label: 'Min Height',
        type: 'text',
        defaultValue: getDefault('minHeight'),
        placeholder: 'e.g., 100px, 5rem',
        category: 'style',
      },
      {
        key: 'backgroundColor',
        label: 'Background Color',
        type: 'color',
        defaultValue: getDefault('backgroundColor'),
        category: 'style',
      },
      {
        key: 'color',
        label: 'Text Color',
        type: 'color',
        defaultValue: getDefault('color'),
        category: 'style',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        type: 'range',
        defaultValue: getDefault('opacity'),
        min: 0,
        max: 1,
        step: 0.01,
        category: 'style',
      },
      {
        key: 'marginTop',
        label: 'Margin Top',
        type: 'text',
        defaultValue: getDefault('marginTop'),
        placeholder: 'e.g., 0, 10px, 1rem',
        category: 'style',
      },
      {
        key: 'marginRight',
        label: 'Margin Right',
        type: 'text',
        defaultValue: getDefault('marginRight'),
        placeholder: 'e.g., 0, 10px, 1rem',
        category: 'style',
      },
      {
        key: 'marginBottom',
        label: 'Margin Bottom',
        type: 'text',
        defaultValue: getDefault('marginBottom'),
        placeholder: 'e.g., 0, 10px, 1rem',
        category: 'style',
      },
      {
        key: 'marginLeft',
        label: 'Margin Left',
        type: 'text',
        defaultValue: getDefault('marginLeft'),
        placeholder: 'e.g., 0, 10px, 1rem',
        category: 'style',
      },
    ],
    advanced: [
      {
        key: 'required',
        label: 'Required',
        type: 'checkbox',
        defaultValue: getDefault('required'),
        category: 'advanced',
      },
      {
        key: 'disabled',
        label: 'Disabled',
        type: 'checkbox',
        defaultValue: getDefault('disabled'),
        category: 'advanced',
      },
      {
        key: 'className',
        label: 'CSS Class',
        type: 'text',
        defaultValue: getDefault('className'),
        placeholder: 'custom-class-name',
        category: 'advanced',
      },
    ],
  },
};


