const mongoose = require("mongoose");
const { Schema } = mongoose;

const websitePageSchema = new Schema({
  projectId: {
    type: Schema.Types.ObjectId,
    ref: "userProjects",
    required: true
  },
  name: { 
    type: String, 
    required: true, 
    trim: true,
    lowercase: true
    // name is unique identifier, non-changeable once created
  },
  slug: {
    type: String,
    required: true,
    trim: true,
    lowercase: true,
    default: function() {
      // Default slug is the name if not provided
      return this.name || '';
    }
  },
  displayName: { 
    type: String, 
    required: true, 
    trim: true 
  },
  pageType: {
    type: String,
    enum: ["default", "service"],
    default: "default",
    required: true,
    trim: true,
    lowercase: true,
  },
  serviceId: {
    type: Schema.Types.ObjectId,
    ref: "Service",
    required: false
  },
  locationId: {
    type: Schema.Types.ObjectId,
    ref: "BusinessLocation",
    required: false
  },
  /** When true, section content is generated per location (+ global null for bulk). */
  perLocationContent: {
    type: Boolean,
    default: false,
  },
  description: { 
    type: String, 
    trim: true 
  },
  /** When false, page is hidden from the live site and navigation */
  isPublished: {
    type: Boolean,
    default: true,
  },
  // Components/sections assigned to this page
  componentIds: [{
    componentId: {
      type: Schema.Types.ObjectId,
      ref: "WebsiteComponent",
      required: true
    },
    componentVariant: {
      type: String,
      required: true,
      trim: true,
      lowercase: true
    } // e.g., "hero_a", "cta_a" - full uniqueId with variant
  }],
  /** Per-page SEO (single active entry in array). Replaces legacy SeoSettings collection. */
  seoSettings: {
    type: [{
      meta_title: { type: String, default: "" },
      meta_description: { type: String, default: "" },
      meta_keywords: { type: String, default: "" },
      meta_image: { type: String, default: "" },
      canonical_url: { type: String, default: "" },
      og_title: { type: String, default: "" },
      og_description: { type: String, default: "" },
      og_image: { type: String, default: "" },
      og_type: { type: String, default: "website" },
      og_site_name: { type: String, default: "" },
      twitter_card: { type: String, default: "summary_large_image" },
      twitter_site: { type: String, default: "" },
      robots: { type: String, default: "index,follow" },
      favicon: { type: String, default: "" },
      structured_data: { type: String, default: "" },
      language: { type: String, default: "en" },
      source: { type: String, default: "manual" },
      /** SEO status: 0 = pending, 1 = generated by AI, 2 = manual entry */
      status: { type: Number, default: 0, enum: [0, 1, 2] },
      /** Log of SEO generation attempts (success/failure with OpenAI response) */
      log: [{
        timestamp: { type: Date, default: Date.now },
        success: { type: Boolean, required: true },
        message: { type: String, default: "" },
        attempt: { type: Number, default: 1 },
        responseSnippet: { type: String, default: "" }, // First 500 chars of AI response for debugging
      }],
      updatedAt: { type: Date, default: Date.now },
    }],
    default: [],
  },
}, { 
  timestamps: true 
});

// Create compound unique index on projectId + name (name is unique per project, non-changeable)
websitePageSchema.index({ projectId: 1, name: 1 }, { unique: true });
websitePageSchema.index(
  { projectId: 1, pageType: 1, serviceId: 1, locationId: 1 },
  {
    unique: true,
    partialFilterExpression: {
      pageType: "service",
      serviceId: { $exists: true },
      locationId: { $exists: true }
    }
  }
);
// Create index on projectId for faster lookups
websitePageSchema.index({ projectId: 1 });
// Note: Removed name_1 index - name should only be unique per project, not globally
// Create index on slug for faster lookups
websitePageSchema.index({ slug: 1 });

module.exports = mongoose.model("WebsitePage", websitePageSchema);

